### ISSUE TITLE
General image annotation also possible?

### ISSUE THREAD

**Issue by poVoq** [ayselafsar/dicomviewer#1]
Very cool project and a big surprise as I just asked for a very similar tool on the NC forums:
https://help.nextcloud.com/t/annotate-images-app/26603

Any chance this can also easily be used for non DICOM pictures, or a way to turn regular photos into DICOM annotations easily?

I am imagining a workflow that lets you open any picture file on your Nextcloud by clicking the (...) button that has an option to annotate, which would direct you to this app (and if technically necessary create a .dcm file with the same name as the picture automatically).

Thanks for considering this.

**Comment by ayselafsar** [comment]
@poVoq We can definitely display regular images like PNG and JPEG with some implementation using [cornerstoneWebImageLoader](https://github.com/cornerstonejs/cornerstoneWebImageLoader) but the main focus will be medical images. Also, persisting annotations would be great.

**Comment by poVoq** [comment]
Ok cool. Looking forward to a future release with JPEG and PNG support.

Thanks!

**Comment by ayselafsar** [comment]
Closed the issue because the main focus is currently on DICOM images.
