### ISSUE TITLE
App "image" / Thumbnail

### ISSUE THREAD

**Issue by guinhas** [ayselafsar/dicomviewer#10]
Hi @ayselafsar ,

Just tried version 0.0.3 and everything seems to be working! Thank you very much for all your latest fixes =). I noticed that when installing DICOM Viewer through the nextcloud app "store", the DICOM Viewer app has no thumbnail/image, I just get a rotating circle and no image appears. Again, thank you very much for your work, it is greatly appreciated! Is there a way to support your work, donations, patreon?

**Comment by ayselafsar** [comment]
Hi @guinhas 

Thanks for the report. I think it is a Nextcloud improvement to handle app image urls better. I have already created [a pull request](https://github.com/nextcloud/usercontent.apps.nextcloud.com/pull/3) in Nextcloud. I will leave this issue open and apply a fix in DICOM Viewer according to the status of that pull request.

You can support me on patreon: https://www.patreon.com/ayselafsar

Thank you for your support! :smile:

**Comment by ayselafsar** [comment]
Fixed.
