### ISSUE TITLE
Support for NextCloud 28

### ISSUE THREAD

**Issue by martoncs** [ayselafsar/dicomviewer#102]
NextCloud 28 has been released for some time, but this app is marked as incompatible.  Is there a plan for support for NC28?

**Comment by fliot** [comment]
Beyond not being "validated" for Nextcloud 28,
This application seems even not be triggered, I personally didn't get a single chance to make it working (no preview, no metadata, no log...).
Regards.

**Comment by ayselafsar** [comment]
Hey @martoncs @fliot 
We are currently working on a new version with new features that will support Nextcloud 28+ which is based on new File API. It will be released soon.
Thanks for your patience!

**Comment by randall11GB** [comment]
@ayselafsar that is awesome.  we use it all day, it is our goto. look forward to the new version.

**Comment by komoricodrutz** [comment]
Thank you! Looking forward to it!

**Comment by oss001** [comment]
Hi, @ayselafsar any timeline update on when support for NC28 can be expected? Waiting patiently in the sidelines...

**Comment by ayselafsar** [comment]
Hello @oss001 
Thanks for your interest!

We're planning to release a new version by the next month. Please feel free to reach out at [aysel.afsar@gmail.com](mailto:aysel.afsar@gmail.com) for a specific feature you're interested in.

**Comment by randall11GB** [comment]
That is great! We are so excited to get new release.  Thank you for all your hard work.  i have advised our team to expect NC28 interoperability next month. Wishing your team great success.

**Comment by eimparas** [comment]
Any updates regarding the new release ? @ayselafsar mentrioned that _next month_ will the new version be released.  I guess , since the comment was posted 3 weeks ago , there is one more week  till the release  :)

**Comment by marceloleiva2016** [comment]
Hola @ayselafsar ...esperamos con ansias la nueva version de dicom viewer para NC28. Saludos desde argentina

**Comment by eimparas** [comment]
Its out ! https://github.com/ayselafsar/dicomviewer/blob/master/changelog.md#200---2024-03-18 ! TY @ayselafsar

**Comment by nursoda** [comment]
@martoncs @ayselafsar Thanks! You may want to close this issue.

**Comment by ayselafsar** [comment]
Thank you all for your support!

v2.0.0 was released as a beta version. This is a major release with a great viewer integration which has lots of new features. Feel free to report any issues you may experience in this version, so we will try to fix them as soon as possible.

Note that "Open with DICOM Viewer" option at folder level is not available in this version. Instead, you could open folder in Nextcloud and click any DICOM file with `.dcm` extension, then the viewer will open that DICOM file and load all other DICOM files with `.dcm` extension in that folder and its sub folders. Since that folder-level option is not available, you should have '.dcm' extension for all of your DICOM files to be opened.

**Comment by oss001** [comment]
Thank you Aysel!
________________________________

**Comment by randall11GB** [comment]
Thank you for this. My team and I really appreciate this.
Warm regards.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by eimparas** [comment]
> Note that "Open with DICOM Viewer" option at folder level is not available in this version

This was a feture that was heavily used in my deployment . The method that @ayselafsar described above does not work for me . 
Will this return on the plugin or the newer nextcloud version "broke" this option for good ? 

best regards
