### ISSUE TITLE
Privacy concern: 2.0.0 loads Google fonts (and uses unpkg.com)

### ISSUE THREAD

**Issue by nursoda** [ayselafsar/dicomviewer#104]
**Describe the bug**
Note that this might sound strange in some areas of the world, but EU data protection authorities and privacy advocats don't like apps that intetrate 3rd party services without data protection agreement with that 3rd party. And, Nextcloud is all about being self-contained, right? So:

In 2.0.0, resources are loaded from fonts.googleapi.com. This is unnecessary since all Google Fonts available that way are free to copy and to be packaged with the app. Please to so and avoid ANY network access to 3rd party servers.

This also applies to unpkg.com. While I have not investigated what it is used for, the sheer fact of it's use is a no-go for privacy-focused solutions such as Nextcloud (apps).

**To Reproduce**
1. Install DICOM viewer 2.0.0
2. Open a DICOM directory
3. Open DevTools of your browser, open network tab
4. Open any DICOM file (currently not working for me due to the [subdirectory bug](https://github.com/ayselafsar/dicomviewer/issues/103#issuecomment-2007930620))
5. Check connections made in DevTools or with any other tool

**Expected behavior**
No external connections.
IF absolutely necessary, make sure an admin installing the app must be informed by the app about such connections.

**Screenshots**
![Screenshot_20240320_002910](https://github.com/ayselafsar/dicomviewer/assets/8425483/238b499b-0e2d-40a1-a6bc-db9a5742292a)

**Client/Server details:**
 - OS/Browser: irrelevant
 - Server: irrelevant

DICOM viewer app version: 2.0.0

**Comment by ayselafsar** [comment]
Moved to https://github.com/acanio/acanio-viewer/issues/1
