### ISSUE TITLE
DICOM Viewer displays black screen. Previews are OK.

### ISSUE THREAD

**Issue by elrond716smith** [ayselafsar/dicomviewer#111]
Clicking on dicom file or "Open with DICOM Viewer" open new tab with black page:
![image](https://github.com/ayselafsar/dicomviewer/assets/55858071/f0c4c9ad-ed40-4d12-a17c-479dfd9c06c6)

Previews are ok:
![image](https://github.com/ayselafsar/dicomviewer/assets/55858071/7933b2f8-bd2f-49b4-89e1-23db3186e26b)

- OS: Windows 11, Arch Linux
 - Browser Chrome, Firefox

Nextcloud installed in docker-compose
Version: 28.0.4

DICOM viewer app version: 2.1.1

Nextcloud log:
`JsonException
Malformed UTF-8 characters, possibly incorrectly encoded
/var/www/html/lib/public/AppFramework/Http/JSONResponse.php
рядок 71
undefinedundefinedjson_encode(
  [
    [
      [
        "1.2.410.200051.1707735840",
        "20240212",
        "130342",
        "STUDY_DESCRIPTION",
        null,
        "And 8 more entries, set log level to debug to see all entries"
      ]
    ]
  ],
  4194305
)
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php
рядок 182
OCP\AppFramework\Http\JSONResponse->render()
/var/www/html/lib/private/AppFramework/App.php
рядок 184
OC\AppFramework\Http\Dispatcher->dispatch(
  [
    "OCA\\DICOMViewer\\Controller\\DisplayController",
    [
      "OC\\AllConfig"
    ],
    [
      "OC\\AppFramework\\Logger"
    ],
    [
      "OC\\Files\\Type\\Detection"
    ],
    [
      "OC\\Files\\Node\\LazyRoot"
    ],
    [
      "OC\\Share20\\Manager"
    ],
    [
      "OC\\User\\Session"
    ],
    "/var/www/html/custom_apps/dicomviewer/js/public/viewer",
    "/var/www/html/custom_apps/dicomviewer/js/public/viewer/assets",
    "/var/www/html/custom_apps/dicomviewer",
    "/var/www/html/data"
  ],
  "getDICOMJson"
)
/var/www/html/lib/private/Route/Router.php
рядок 315
OC\AppFramework\App::main(
  "OCA\\DICOMViewer\\Controller\\DisplayController",
  "getDICOMJson",
  [
    "OC\\AppFramework\\DependencyInjection\\DIContainer"
  ],
  [
    "dicomviewer.display.getDICOMJson"
  ]
)
/var/www/html/lib/base.php
рядок 1069
OC\Route\Router->match(
  "/apps/dicomviewer/dicomjson"
)
/var/www/html/index.php
рядок 39
OC::handleRequest()`

**Comment by elrond716smith** [comment]
It looks like problem in encoding. This DICOMs have not UTF-8 encoding, but cp1251. Can support of cp1251 encoding be added?
Found another CBCT with UTF-8 encoding - no problem with DICOM viewer:
![image](https://github.com/ayselafsar/dicomviewer/assets/55858071/9b2d5eeb-97f5-4381-b9a7-d41d70353971)

**Comment by elrond716smith** [comment]
This is a link with DICOMs, witch are not showing up in DICOM Viewer:
[https://elrond.org.ua/s/p9iowYdGG5Dyfxe](url)

**Comment by copemande** [comment]
Comparing the behavior & the error log, this seems to be identical to  bug#110 ->  https://github.com/ayselafsar/dicomviewer/issues/110

**Comment by osbarcelos79** [comment]
Same here.  
Ubuntu 20.04 
PHP 8.2
Nextcloud 28.0.5

**Comment by DimonW88** [comment]
docker nextcloud 29.0.0 the problem persists
