### ISSUE TITLE
Not loading the dcm files

### ISSUE THREAD

**Issue by loxK** [ayselafsar/dicomviewer#117]
The files I try to view were working with previous version of the app (under nextcloud 27).

The preview isn't showing the image, but I can see attributes :

![image](https://github.com/ayselafsar/dicomviewer/assets/136687/2ce61e6c-0387-4b1a-96cf-4ae16952b9b7)

When I click the DCM file, it opens the tabs but keeps loading forever :

![image](https://github.com/ayselafsar/dicomviewer/assets/136687/e3d1f60a-93a1-4f65-88c3-605ded88c322)

I have this error in console :

`Error: Unable to query for SeriesMetadata without StudyInstanceUID`

**Client details:**
 - OS: Ubuntu
 - Browser: chrome and firefox
 - Version: Browser latest
 - Device: desktop

**DICOM viewer app version:** latest

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** Mariadb

**PHP version:** 8.2

**Nextcloud version:** 28.0.6

**Comment by ayselafsar** [comment]
@loxK As I see, StudyInstanceUID is not available for the instance. If possible, could you please share your anonymized data?

**Comment by ayselafsar** [comment]
@loxK The instance you try to load is "Media Storage Directory Storage", not an image storage. It is not supported. See below for attributes:

<img width="518" alt="Invalid DICOM Instance" src="https://github.com/ayselafsar/dicomviewer/assets/8215016/99884d01-3feb-4ba9-bd81-bde8e872551f">

**Comment by loxK** [comment]
It used to work with previous version of the app. Why isn't it supported anymore ?
This is all I get on the CD-ROM from my hospital's radiography center.
