### ISSUE TITLE
No Image - Nextcloud 13.0.2

### ISSUE THREAD

**Issue by mriosfer** [ayselafsar/dicomviewer#13]
OS: CentOS 7.4
CPU: 4  CPU
RAM: 8 GB DDR4
Disk SSD

Plesk 17.8 Installed
NGINX+PHP 7.2
PHP Max memory: 1024MB per process

DCM : 320 MB
LOADTIME: Less than 10 secs

It load metadata info in each corner but show a black screen instead image.

Checked:  error.log apache and nginx and dont drop any error.

**Comment by ayselafsar** [comment]
Hi @mriosfer 
Thanks for the report. It might be a problem with DICOM file, is there any chance of sending DICOM file in anonymized version?

**Comment by mriosfer** [comment]
OK after a debug from @ayselafsar our DICOM file dont follow the standards.. Thanks so much!
