### ISSUE TITLE
only one picture

### ISSUE THREAD

**Issue by unecc** [ayselafsar/dicomviewer#135]
Hi, i've downloaded dicom viewer for using inside nextcloud

![image](https://github.com/user-attachments/assets/286bc2d4-59bc-4b7b-9e7a-93d84129bf26)

it can view only 1 only image of scans.

Online tools like this, works perfect
https://www.imaios.com/en/imaios-dicom-viewer
https://www.rubomedical.com/dicom_files/dicom_viewer_0012.zip

It's a bug?

**Comment by unecc** [comment]
anyone?

**Comment by FlorianHeigl** [comment]
hi: i think i got the same issue but am not sure yet due to an upgrade i made elsewhere.

**Comment by ayselafsar** [comment]
We'll release a new version to fix the issue soon. Thanks for reporting!
