### ISSUE TITLE
dicomviewr will try to load benchmarks json files from the nextcloud root folder. 404 error for /benchmarks/

### ISSUE THREAD

**Issue by lexxai** [ayselafsar/dicomviewer#137]
**Describe the bug**
dicomviewr will try to load benchmarks json files from the nextcloud root folder, not from /apps/dicomviewer/ncviewer/

**To Reproduce**
Open app
404 error for /benchmarks/d-intel.json

**Expected behavior**
200 status code 

**Screenshots**
404 error for /benchmarks/d-intel.json
![2024-12-19 213108](https://github.com/user-attachments/assets/20e6b7b5-5bdc-471d-b003-9d3ad3bc1645)

<details>
<summary>Server details</summary>
**DICOM viewer app version:**  1.0.2 / 2.2.1

**Operating system**: FreeBSD

**Web server:** NGINX

**Database:** 

**PHP version:** 8.3.x

**Nextcloud version:** (30.0.4.1)

</details>

temp solution for nginx.

```nginx
        location ~ ^/benchmarks/(d|m)-[a-z\-]+\.json$ {
           root /usr/local/www/nextcloud/apps/dicomviewer/js/public/viewer;
           try_files $uri  /index.php$request_uri;
        }
```

**Comment by ayselafsar** [comment]
Fixed by https://github.com/acanio/acanio-viewer/pull/9
