### ISSUE TITLE
App installed but nothing happens

### ISSUE THREAD

**Issue by beankylla** [ayselafsar/dicomviewer#14]
Hello,

Happy nextcloud user on version 13.0.2 on ubuntu 16.04.1 with nginx.

I installed the Dicomviewer, and tried to visualize some Dicom files (example attached) but really nothing happens.

i also tried:

1) renaming the files to .dcm but behavior is unchanged. 
2) downloading a sample dicomfile from another ticket to see if i could visualize it. (attached)
[sample.zip](https://github.com/ayselafsar/dicomviewer/files/1992558/sample.zip)

Same happens. when i click on a file it downloads and when i click on "information" i just see standard file info

am i doing something wrong?

**Comment by beankylla** [comment]
so at first i had no mimetypemappung.json file, so i disabled, removed the file then i reinstalled it, and saw it appear and now it's working!
Seems there was an issue with the first install.
Thanks for your support!

**Comment by warnerbryce** [comment]
I had the same problem but mimetypemapping.json was there. 
I just had to do a service nginx (or apache2) restart, and it was done.
