### ISSUE TITLE
does dicomviewer work with anonymous users?

### ISSUE THREAD

**Issue by Mersault75** [ayselafsar/dicomviewer#16]
Hi there!

First of all, nice job! It is a very helpful app. We've recently found that if we share a folder with dicoms via email with an external user, when he tries to see the dicom file, the app does not start. It does not raise any error or message. We have other app's, such as onlyoffice or pdf viewer, that are working with anonymous users. Is it a normal behaviour or can it considered as an issue?

Thanks!!

**Comment by wjwieland** [comment]
I believe that the viewer itself would have to reside on the local machine for them to receive a file and view it.  As it is, the viewer is being loaded in the browser as a javascript app, which allows one to see the file(s).  So the viewer app is in a way tied to NextCloud at present. 

I suspect there could be some HIPPA issues with passing images back and forth via email amongst medical professionals....

**Comment by ayselafsar** [comment]
Thanks for the report. Please give it a try by sharing a folder containing dicom files with public link in version 1.0.0. Note that it does not work when shared a single dicom file directly.
