### ISSUE TITLE
Compatibility with Nextcloud 14

### ISSUE THREAD

**Issue by juliushaertl** [ayselafsar/dicomviewer#17]
Hi @ayselafsar,

as you may have already seen, we have entered the beta phase for the release of Nextcloud 14. We try to keep up compatibility with older apps, but in some cases apps need some adjustments to properly work on new Nextcloud releases. With Nextcloud 14 there have been quite some changes in that regard:

You can find a list of all critical changes for app developers and admins at https://github.com/nextcloud/server/issues/7827 You can run `occ app:check-code` to validate that there are no issues with deprecated or private message calls. 

One critical change is the overall restructuring of the main template (https://github.com/nextcloud/server/pull/9982) that might require some adjustments in your app.

We would be very pleased if you can make your app compatible with Nextcloud 14 and release a new version to the app store, so that users can properly test it and the upgrade experience to Nextcloud 14 will be even better than before.

Feel free to ask, if you have any questions regarding making your app compatible with Nextcloud 14. 

Thanks for being part of the Nextcloud community and for all the effort you put into providing this app :rocket:

**Comment by ayselafsar** [comment]
Hi @juliushaertl 
Thank you for the update. I recently made it compatible with Nextcloud 14.
