### ISSUE TITLE
Scroll bar and hidden menus

### ISSUE THREAD

**Issue by guinhas** [ayselafsar/dicomviewer#18]
Hi,
This is turning out to be a really awesome app for nextcloud! A few months ago I had to uninstall DICOM Viewer from my nextcloud machine because it was causing troubles, like the log in page not appearing. I just got a blank error page saying something went wrong and the page couldn't be found. Uninstalling DICOM Viewer fixed that. Now I came back to check on the project and just look at it! It is working beautifully! With slice scrolling! Like a real CT or MRI workstation! Just awesome! Thank you so much! If I can make a little suggestion, a scroll bar in the left series column, like the one in the image viewer itself (to the right), could be a nice addition. Also, while DICOM Viewer is open, you can't access the nextcloud top right menus, like PEOPLE/CONTACTS or the other one where the +APPS, OPTIONS and LOG OUT buttons are. The menus are hidden behind the DICOM Viewer window. Is this the expected behaviour? Thank you!

**Comment by ayselafsar** [comment]
Thank you for your feedback! 

It is expected that top bar is hidden in Nextcloud 14.

**Comment by guinhas** [comment]
Thank you! I have a couple more suggestions, I'm going to open a new issue, but if you want I can just add them here. Thank you very much!

**Comment by wjwieland** [comment]
This size of those scroll bars is tiny, almost invisible (the scroll bar to the right when viewing a series).  I actually discovered it by accident.  Just a couple more pixels wide would be helpful!  Hope that is helpful.
Great extension!

**Comment by wjwieland** [comment]
I just update to NC 14.01 and the first thing I checked was to see if Dicomviewer worked:  It did, very nicely!  And the series scroll bar is now easy to see and use as well.  This just keeps getting better...

**Comment by ayselafsar** [comment]
This issue is fixed (currently in development branch) and will be released in the next version.
