### ISSUE TITLE
Full screen and Sort

### ISSUE THREAD

**Issue by guinhas** [ayselafsar/dicomviewer#19]
Hi,
When using DICOM Viewer with firefox for android, the upper tools bar occupies half the screen of my phone. Maybe a toggle full screen button could be a solution to have the image occupy the entire screen, or a hide tool bar option? Also when using my phone, as it has just 1gb memory, when opening large exams firefox and chrome just shutdown. Could a "Sort with DICOM Viewer" option, next to the "Open with DICOM Viewer" solve this? The sort option would sort an entire Exam directory into several Series directories, named after the different Series found. These Series directories would be created inside the Exam directory and the DICOM files would be moved to the corresponding Series directories. This would allow to open just individual Series instead of an entire Exam, saving memory. This Sort could also add the .dcm extension to DICOM files that had no extension, as opening individual files with one mouse click only works when a .dcm extension is present. Maybe these ideas are completely beyond the scope of what you intended for DICOM Viewer. What do you think? Thank you very much!

**Comment by ayselafsar** [comment]
Hi @guinhas,

Thank you for your feedback!

Toolbar takes up too much space in mobile devices. That will be fixed.

The other issue might require some server-side work like parsing DICOM files on server. If the app crashes in parsing files in mobile devices, we might need to move this to server side but if it crashes while displaying DICOM images, it needs better memory management on client. Is there any chance you share the anonymized version of your large case with me to investigate?

**Comment by guinhas** [comment]
Hi,
My very old laptop (almost 15 years old...), with only 1gb memory and running Ubuntu, is able to handle the exam just fine, I don't know if some SWAP is involved or not... On my android phone, Firefox and Chrome shut down while Loading the exam. Chrome shuts down around 60%-70% and Firefox above 90%. Firefox (didn't test Chrome), also crashes while browsing a large image gallery in nextcloud, so this isn't particular do DICOM Viewer, that's why I suggested dividing the Exam directory in smaller Series directories. I should just buy a new phone... This particular case I can't share as it isn't anonymized, but I'm going to export a few anonymized exams from the MRI and CT workstations from my workplace. I'll share them after I tested them to see if they crash the browsers. Thank you very much!

**Comment by guinhas** [comment]
Hi,
Sorry for taking so long to send an anonymized case, but I found out that the Siemens MRI workstation doesn't do a very good job at anonymization... After careful analysis of the DICOM details, a lot of sensitive information isn't anonymized... Like physician and technician names, Institution name, time and date of exam, etc... I'll have to find a good tool to anonymize the case before i send it, sorry... Again, sorry for bringing this up again, it might be beyond the scope of what you intended DICOM Viewer to be, but a "Sort with DICOM Viewer" option with an anonymization function, like "Sort for Clinical Trials" would be a really cool tool. Also the Siemens workstation exports exams as .IMA files, making it impossible to see the DICOM attributes of individual files in the details section of nextcloud. If DICOM Viewer could also recognize .IMA as DICOM files, as it does for .dcm files, would also be very useful. Just for testing, I renamed a .IMA file to .dcm and DICOM Viewer was able to work with that file as if it was a .dcm. I know you must have a lot of other things that are much more important for DICOM Viewer as a project, instead of these Sort "functions/tools", but I just had to mention it. Thank you very much!

**Comment by wjwieland** [comment]
#guinhas
Some DICOM viewers/editors which might assist you with better anonymization.
https://technologyadvice.com/blog/healthcare/5-dicom-viewers/ 
Hope that is helpful.  

I run on Linux 99% of the time, so GinkoCad is my goto.

**Comment by ayselafsar** [comment]
Hi @guinhas,

Thank you for the update.

It looks like the default image cache size (1 GB) exceeds the maximum memory size of the browser in that case so reducing the cache size might be helpful. I will add a setting to manually set the cache size but I should firstly confirm that. I might send you a test build with low cache size like 128 MB.

Btw, I will add .IMA extension to support in DICOM Viewer.

**Comment by guinhas** [comment]
Hi!
Wow, thank you! That's awesome! After testing A LOT of different parameters and options with gdcmanon, I finally managed to be satisfied with the level of anonymization achieved on the exam that was causing trouble. If you want I can send it for testing, it's a bit large though, around 360MB.

**Comment by ayselafsar** [comment]
Hi @guinhas,

I set the max image cache to 128 MB. Could you try the attached version on your mobile device? You should remove the current version firstly and extract and put this into apps/dicomviewer folder manually. Please let me know if you need any help.

[dicomviewer.tar.gz](https://github.com/ayselafsar/dicomviewer/files/2369055/dicomviewer.tar.gz)

Thanks

**Comment by guinhas** [comment]
Hi @ayselafsar,

I'm sorry but it didn't work, firefox crashed while loading the images. But don't worry about it, it has to be a problem with my phone, not DICOM Viewer. Right now I don't have any other android devices with me, but I'll test the shield k1 tablet as soon as I can (it's not with me right now...). My laptop opened the exam without any problem, like it did before. Forget about it! It must be a problem with lineageos memory management, or with firefox or maybe the two just don't get along. Thank you very much for your help and for your efforts and I'm really sorry for giving you the extra trouble!

**Comment by ayselafsar** [comment]
Hi @guinhas 

Thanks for testing, no worries.

**Comment by ayselafsar** [comment]
Fixed the toolbar space on small screens, will be released in the next version.
