### ISSUE TITLE
No pictures are shown

### ISSUE THREAD

**Issue by tuxmaster** [ayselafsar/dicomviewer#24]
### Steps to reproduce
1. Upload the DVD content into NC
2. Navigate to the folder

### Expected behaviour
That the images are shown

### Actual behaviour
Only the row files are show, like normal files

### Server configuration

**Operating system**: CentOS 7.5

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** 14.0.3

**Where did you install Nextcloud from:** Tar archive

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - dicomviewer: 1.0.2
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - piwik: 0.4.1
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXX.XXX.XX"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 83886080,
        "allowZipDownload": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "log_type": "syslog",
        "loglevel": "1",
        "logfile": "",
        "logtimezone": "Europe\/Berlin",
        "log_authfailip": true,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "maintenance": false,
        "asset-pipeline.enabled": true,
        "updatechecker": false,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "overwrite.cli.url": "https:\/\/speicher.terrortux.de",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

### Client configuration
**Browser:** Firefox

**Operating system:** Fedora 28

#### Nextcloud log (data/owncloud.log)
Nothing was logged

#### Browser log
Nothing was logged

http://aeskulap.nongnu.org/ and the java viewer from the DVD can show both images sets.
Set1:
|-- DICOM
|   `-- PA000001
|       `-- ST000001
|           `-- SE000001
|               |-- IM000001
|               `-- IM000002
`-- DICOMDIR

Set2:
|-- DICOM
|   `-- PA000001
|       `-- ST000001
|           |-- SE000001
|           |   |-- IM000001
|           |   |-- IM000002
|           |   |-- IM000003
|           |   |-- IM000004
|           |   `-- IM000005
|           |-- SE000002
|           |   |-- IM000001
|           |   |-- IM000002
|           |   |-- IM000003
|           |   |-- IM000004
|           |   |-- IM000005
|           |   |-- IM000006
|           |   |-- IM000007
|           |   |-- IM000008
|           |   |-- IM000009
|           |   |-- IM000010
|           |   |-- IM000011
|           |   |-- IM000012
|           |   |-- IM000013
|           |   |-- IM000014
|           |   `-- IM000015
|           |-- SE000003
|           |   |-- IM000001
|           |   |-- IM000002
|           |   |-- IM000003
|           |   |-- IM000004
|           |   |-- IM000005
|           |   |-- IM000006
|           |   |-- IM000007
|           |   |-- IM000008
|           |   |-- IM000009
|           |   |-- IM000010
|           |   |-- IM000011
|           |   |-- IM000012
|           |   |-- IM000013
|           |   |-- IM000014
|           |   |-- IM000015
|           |   |-- IM000016
|           |   |-- IM000017
|           |   |-- IM000018
|           |   |-- IM000019
|           |   |-- IM000020
|           |   |-- IM000021
|           |   `-- IM000022
|           |-- SE000004
|           |   |-- IM000001
|           |   |-- IM000002
|           |   |-- IM000003
|           |   |-- IM000004
|           |   |-- IM000005
|           |   |-- IM000006
|           |   |-- IM000007
|           |   |-- IM000008
|           |   |-- IM000009
|           |   |-- IM000010
|           |   |-- IM000011
|           |   |-- IM000012
|           |   |-- IM000013
|           |   |-- IM000014
|           |   |-- IM000015
|           |   |-- IM000016
|           |   |-- IM000017
|           |   |-- IM000018
|           |   |-- IM000019
|           |   |-- IM000020
|           |   |-- IM000021
|           |   `-- IM000022
|           |-- SE000005
|           |   |-- IM000001
|           |   |-- IM000002
|           |   |-- IM000003
|           |   |-- IM000004
|           |   |-- IM000005
|           |   |-- IM000006
|           |   |-- IM000007
|           |   |-- IM000008
|           |   |-- IM000009
|           |   |-- IM000010
|           |   |-- IM000011
|           |   |-- IM000012
|           |   |-- IM000013
|           |   |-- IM000014
|           |   |-- IM000015
|           |   |-- IM000016
|           |   |-- IM000017
|           |   |-- IM000018
|           |   |-- IM000019
|           |   |-- IM000020
|           |   |-- IM000021
|           |   |-- IM000022
|           |   |-- IM000023
|           |   |-- IM000024
|           |   |-- IM000025
|           |   |-- IM000026
|           |   |-- IM000027
|           |   `-- IM000028
|           `-- SE000006
|               |-- IM000001
|               |-- IM000002
|               |-- IM000003
|               |-- IM000004
|               |-- IM000005
|               |-- IM000006
|               |-- IM000007
|               |-- IM000008
|               |-- IM000009
|               |-- IM000010
|               |-- IM000011
|               |-- IM000012
|               |-- IM000013
|               |-- IM000014
|               |-- IM000015
|               |-- IM000016
|               |-- IM000017
|               |-- IM000018
|               |-- IM000019
|               |-- IM000020
|               |-- IM000021
|               |-- IM000022
|               |-- IM000023
|               |-- IM000024
|               `-- IM000025
`-- DICOMDIR

**Comment by tuxmaster** [comment]
After play around an new menu was shown on "...", that will open it.
It is possible to make the easier to find?

**Comment by wjwieland** [comment]
I am curious about how the files were put on the NC system: Were they uploaded via the web interface....or were they copied into the (username)/files/(somefolder).... or were they copied to a location on your local machine and then synced with the NC sync client?

**Comment by tuxmaster5000** [comment]
Simple copy from the dvd  to an folder which are synchronized by the nc client.

**Comment by wjwieland** [comment]
> Simple copy from the dvd to an folder which are synchronized by the nc client.

tuxmaster: That should work just fine.  It does on my NC.  To be clear, I run NC on a home server, with NC recently update to latest stable.  Have you looked in the 'apps' section of NC to ensure that DICOM viewer is at the latest release?

**Comment by wjwieland** [comment]
Does the elipses ... display "Open with DICOM Vvewer" when selected on the folder in which you placed your images? If not, I have to wonder if the problem is with the images themselves?  Are they viewable in other software like Ginko or DICOMViewr?

**Comment by tuxmaster5000** [comment]
Yes this will work like noted on commend https://github.com/ayselafsar/dicomviewer/issues/24#issuecomment-429552116 But it will not very ease to find.

**Comment by ayselafsar** [comment]
For ease of use, we can add a setting whether to show all dicom images in the same folder and all sub folders, or only the selected dicom image when a dicom image is clicked to display, so users can change it based on their preferences.

**Comment by tuxmaster5000** [comment]
Yes, it sounds very good.

**Comment by Lars1963** [comment]
Nice to have.

**Comment by ayselafsar** [comment]
Fixed to open the selected image with all images by default. Refer to #54 for the user setting to change this behavior.
Thanks!

**Comment by wjwieland** [comment]
Nice!
