### ISSUE TITLE
php error "Undefined index" when open an folder

### ISSUE THREAD

**Issue by tuxmaster** [ayselafsar/dicomviewer#25]
### Steps to reproduce
1. Open the folder with "Open with DICOM Viewer"

### Expected behaviour
All ok

### Actual behaviour
All ok

### Server configuration
See https://github.com/ayselafsar/dicomviewer/issues/24
PHP error:
{PHP} Undefined index: isSingleDICOMFile at /XXXXX/apps/dicomviewer/lib/Controller/DisplayController.php#47

**Comment by wjwieland** [comment]
I can verify this issues on my system.
Nextcloud version14.04
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Comment by ayselafsar** [comment]
Thanks for the report. This issue is fixed by #29 and will be released in the next version.
