### ISSUE TITLE
Nextcloud 15 compatibility

### ISSUE THREAD

**Issue by violoncelloCH** [ayselafsar/dicomviewer#29]
Nextcloud 15 has been released today. It would be nice if you could update this app to work on Nextcloud 15! Thank you!

**Comment by quassum** [comment]
I second that request!

**Comment by ayselafsar** [comment]
Hi,
Thanks for the report. It will be released soon.

**Comment by violoncelloch** [comment]
Thank you!

**Comment by quassum** [comment]
Great, let me know when and if I can test anything from this side.

**Comment by ayselafsar** [comment]
This issue is fixed (currently in development branch) and will be released in the next version.
