### ISSUE TITLE
PHP previews

### ISSUE THREAD

**Issue by rullzer** [ayselafsar/dicomviewer#3]
Does this viewer also allow generating jpeg/png images? That way we could also create small preview images to display? (that is then done in php).

Or do you know of a library to do this in php?

**Comment by ayselafsar** [comment]
We can generate jpeg/png images with this viewer, but it is all in javascript (client-side). However, I’m not sure if that is what you are looking for. I have no idea if there is such php library.

**Comment by rullzer** [comment]
Ah no. Ok then we'll have to do it with javascript previews for now ;)

Still cool app! If you need any help feel free to dropby in #nextcloud-dev !
