### ISSUE TITLE
Problema 

### ISSUE THREAD

**Issue by dmaderni** [ayselafsar/dicomviewer#4]
Hola, cuando habilito la app, la CPU sube al 70%.. en mysqld. estoy usando nextcloud 13.
gracias y solo comentar que la app es muy util!!!

**Comment by ayselafsar** [comment]
As I understand, this is the issue you posted: "CPU usage gets up to 70% after enabling DICOM Viewer in Nextcloud 13"

If that is correct, i cannot reproduce this issue with Nextcloud 13. Have you tried the latest version, v0.0.2? Are you using the snap version of Nextcloud?

**Comment by dmaderni** [comment]
Hello how are you? thanks for your attention!! with the version, v0.0.2 all
good.
Thank you very much and go ahead with this very interesting project

2018-02-19 17:42 GMT-03:00 Aysel Afsar <notifications@github.com>:

**Comment by ayselafsar** [comment]
Fixed with #7 and will be in the next release.
