### ISSUE TITLE
New title for ROI window

### ISSUE THREAD

**Issue by Lars1963** [ayselafsar/dicomviewer#41]
@ayselafsar @doc-sebastian 

Is a title like e.g. "Presetlevels" or "Window presets" instead of "ROI Window" perhaps less confusing for new users (or other medical professionals apart from radiologists)? 

Should probably best combined with a sub-menu for bones, tissue, etc. as stated by doc-sebastian in closed PR #34
See e.g.
 https://rawgit.com/cornerstonejs/cornerstone/master/example/ctimage/index.html

**Comment by doc-sebastian** [comment]
ROI Window should be fine. Dedicated window presets (bone, lung etc) would 
be a separate feature. I guess you cannot combine it with this tool unless 
implementing a submenu, which might cause trouble for certain devices.


Am 3. Januar 2019 13:33:23 schrieb Lars van Ravenzwaaij 
<notifications@github.com>:

**Comment by doc-sebastian** [comment]
Perhaps after merging #37 renaming "ROI Window" to "Levels ROI" would be less confusing. Then we have "Levels" and "Levels ROI" next to each other with similar functions.

**Comment by Lars1963** [comment]
That's a good idea. Love it.

**Comment by ayselafsar** [comment]
@doc-sebastian @Lars1963 Please update german and dutch translations for "Levels ROI" if needed. Thanks.
