### ISSUE TITLE
Suggestion: DCM Video Support

### ISSUE THREAD

**Issue by nickisashkir** [ayselafsar/dicomviewer#44]
Hello. I would like to suggest support for video DCM files. Several of my DICOM files are ultrasound recordings. Most offline DICOM apps I have can play the video. I would like to be able to play/loop the video through NextCloud's interface. 

I also absolutely love the progress on this and subscribed to patreon! Not much sorry :(

**Comment by ayselafsar** [comment]
Thank you for your request and support!

Multi-frame image support is already on the roadmap and will be implemented soon.

**Comment by skynet-dev** [comment]
can you upgrade your dicom viewer with the latest OHIF update with 2D 3D support, as well the ability to support PACS Server such as DCM4CHEE arc light

**Comment by skynet-dev** [comment]
HI ! I would like to suggest to upgrade your dicom viewer with the latest OHIF update with 2D 3D MPR support, as well the ability to support PACS Server such as DCM4CHEE arc light (Integration)
