### ISSUE TITLE
Development Environment setup guidance

### ISSUE THREAD

**Issue by EsrefDurna** [ayselafsar/dicomviewer#55]
Hello,

I tried to create an development environment setup to contribute to dicomviewer.
Here is the challanges that I get.

There is no guidance on nextcloud development setup.
Running nextcloud on mac is really hard, I tried ubuntu then I have to keep copying my artifacts to that VM.

Same for docker and docker compose as well.

Please explain best practices to create a development environment in readme for new contributors.

Thank you

Esref

**Comment by ayselafsar** [comment]
Hi @EsrefDurna

Thanks for your interest.

We actually assume that our contributors are already familiar with Nextcloud. You can follow [this guide](https://docs.nextcloud.com/server/15/developer_manual/general/devenv.html) and get your questions about Nextcloud App Development answered in [Nextcloud Help Forum](https://help.nextcloud.com).
