### ISSUE TITLE
Dicom protocol - server integration

### ISSUE THREAD

**Issue by skunkr** [ayselafsar/dicomviewer#57]
Hi Everyone,
First, thank you for this product,  it is a really beautiful thing !

My question is regarding any past experience implementation and compatibility with a linux based dicom server,  so our Nextcloud instance to act as close as possible as a PACS server.
IE:  The equipments are directly sending the dicom streams to nextcloud, using multiple ae_titles, and nextcloud users can view the fresh uploaded images.
Any suggestions, or ideas ?
Thank you very much,
Have a great day !

Leo

**Comment by tarekmamdouh** [comment]
i am not sure if I understand the question correctly, but usually any PACS server should provide an implementation of the standard called WADO (Web Access to Dicom Objects) or WADO-RS which is the more recent standard
https://www.dicomstandard.org/dicomweb/retrieve-wado-rs-and-wado-uri/

**Comment by ayselafsar** [comment]
Hi,
I think that @skunkr mentioned DIMSE protocol where some old PACS do not support for dicomWeb. Our priority will be supporting for dicomWeb (QIDO, WADO) first for PACS integration though.
