### ISSUE TITLE
Nextcloud 17 compatibility 

### ISSUE THREAD

**Issue by jotzt** [ayselafsar/dicomviewer#60]
The DICOM viewer is currently not compatible with Nextcloud 17.

**Comment by snapet** [comment]
Any chance of an update to support Nextcloud 17?
Thanks for the work you put into this. Much appreciated!

**Comment by ayselafsar** [comment]
Sorry for the delay. I will release a new version supporting Nextcloud 17 ASAP.

**Comment by ayselafsar** [comment]
Fixed in [v1.2.1](https://github.com/ayselafsar/dicomviewer/releases/tag/v1.2.1)
