### ISSUE TITLE
App cannot open .dcm file if I click on the file directly

### ISSUE THREAD

**Issue by GammaPi** [ayselafsar/dicomviewer#61]
### Steps to reproduce
1.Download and enable this app
2.Upload .dcm
3.Click on it
4.Progress 0% forever
5.Click menu, Click Open in Dicom Viewer
6.Progress 0% to 100%. Dicom file shows flawlessly

### Server configuration
**Nextcloud version:** Docker Nextcloud 16.0.6

**Comment by ayselafsar** [comment]
It might be related to that specific dicom file. Did you try it with another one? If it still does not work, is there any chance to send me the anonymized version of that dicom file to investigate? Thanks!

**Comment by medcloud** [comment]
Hello ayselafsar, first of all, many thanks for this useful DICOM app !
As GammaPi wrote above, I can also reproduce same issue but not on all DICOM files : some of them. But impossible to understand what is the difference between files it works and files it doesn't work...
I am using Chrome Version 83.0.4103.97 (Build officiel) (64 bits) with Nextcloud V17.03

**Comment by powerpaul17** [comment]
I got the same error and after some investigation I realized that the app for some reason tries to scan all my files for dicom files. Which takes a long time.. I don't know why the viewer tries to find all dicom files if I only want to open one.
