### ISSUE TITLE
Support for ZIP Files

### ISSUE THREAD

**Issue by imforumman** [ayselafsar/dicomviewer#62]
So this is a really great idea and just an amazing interface you have created. I love being able to teach interesting cases right out of my cloud, but, it would be so much more convenient if I could access those cases out of a zip file, kind of like using the zip-file as a virtual file system. Just if this is not too much of a hassle...

Thanks for the fantastic work!

**Comment by Enelar** [comment]
This is an important feature for me too. By nature of data backbone in my kubernetes my files are available within 2 seconds delay. I think this is the reason why sometimes the app displays only part of the scan (I have 532 slices, most of the times it loads less than 200). I would LOVE to have support for .dcm.zip files it would make so much more sense. Also it will neglect the issue when only portion of the files are being processed by a client.
