### ISSUE TITLE
Cross Hair Functionality

### ISSUE THREAD

**Issue by rishbaranwal** [ayselafsar/dicomviewer#63]
**Is your feature request related to a problem? Please describe.**

Cross Hair Functionality Implementation

**Describe the solution you'd like**

When user tap anywhere(body part where tapped) on images of one series, can we apply the cross hair functionality so that user is able to view all the related(body part where user clicked somewhat in zoom manner) images of user tapped body part location.

**Comment by ayselafsar** [comment]
@rishbaranwal Thanks for your interest!

This is on our roadmap with reference lines.
