### ISSUE TITLE
ClearCanvas DICOM SERVER integration

### ISSUE THREAD

**Issue by avait1** [ayselafsar/dicomviewer#64]
Hi,
How can I integrate with ClearCanvas DICOM SERVER To read Dicom files through directory ?
Thank You

**Comment by ayselafsar** [comment]
@avait1 Thanks for your interest!

This is related to #57 

Unfortunately, we do not have DICOM server integration yet, but we have a roadmap to support for DICOMWeb. However, I think ClearCanvas DICOM Server supports for DIMSE only which we don't have any plans to support for.
