### ISSUE TITLE
Open Viewer Directly from the Url

### ISSUE THREAD

**Issue by ricardoperovano** [ayselafsar/dicomviewer#67]
Hi!
This issue is not related to any bugs, i was just wondering if it is possible to open the dicom viewer directly from the url instead of clicking on the file, I was trying to call the file url but the dicom viewer does not open.

Any helps ?
Thanks!

**Comment by heibertelf** [comment]
It could be helpful with some dicom files without extension

**Comment by nursoda** [comment]
This also would be helpful when sharing pictures/scans to 3rd party users like another doctor. Today, that 3rd party must be provided with an URL and instructions. Ideal would be if there was a possibility to share in such way (additional URL parameter?) that the viewer starts right away.

**Comment by nursoda** [comment]
OK…is it intentional that a ticket that has not been worked on is "closed as not planned"?
