### ISSUE TITLE
Great ideea but breaking nextcloud

### ISSUE THREAD

**Issue by Aesculapius** [ayselafsar/dicomviewer#7]
Hi,

I love the idea to show DICOM images and even show header information quickly.
But after enabling the app, CPU usage on the database lifts off to 100% for too long and thus it breaks Nextcloud completely. Restarting apache or mysql didn't help, had to disable the app from cli. Even that didn't work... as the occ command didn't get any cpu time for its query? (had to move the app folder after which I could disable it with occ command)

**Comment by ayselafsar** [comment]
Thanks for the report! Could you provide the versions of Nextcloud, PHP and OS?

**Comment by ayselafsar** [comment]
Fixed and will be in the next release.
