### ISSUE TITLE
don't show attribute and preview image

### ISSUE THREAD

**Issue by avangdev** [ayselafsar/dicomviewer#73]
**Describe the bug**
in New nextcloud , attribute and preview image don't show

**Screenshots**
![Screen Shot 2020-05-31 at 5 54 18 PM](https://user-images.githubusercontent.com/42209626/83353656-3c7dea80-a369-11ea-9caf-5ef0eed5c56a.png)

**Comment by ayselafsar** [comment]
Hi @avangdev,

Thanks for the report. It is known issue because of NC 18 release and will be fixed ASAP.

**Comment by Jake-Etherflow** [comment]
Just wanted to say thank you very much for this excellent tool!

If you need anyone to test or resources to resolve please reach out. 

Do these attributes enumerate within fulltextsearch by chance?
