### ISSUE TITLE
Multiple Windows Layout with Reference Lines

### ISSUE THREAD

**Issue by jeff-kissinger** [ayselafsar/dicomviewer#74]
1. Add multiple window layout with up to 9 windows. Image sequences can be dragged to a window or if the window is highlighted and a sequence is selected it will populate in that window.
2. When multiple windows have been selected, add reference lines to the different image planes selected in the other windows.
    Here are some examples: 
Radiant Viewer: https://www.radiantviewer.com/dicom-viewer-manual/cross-reference_lines.html
From the cornerstone.js library: https://tools.cornerstonejs.org/examples/tools/reference-lines.html
OHIF Viewer (Layout icon at top): https://viewer.ohif.org/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170125095722.1

**Comment by ciroiriarte** [comment]
+1 !
