### ISSUE TITLE
Scroll through slices

### ISSUE THREAD

**Issue by guinhas** [ayselafsar/dicomviewer#8]
Hi,

First of all, thank you very much for this project! I have nextcloud 13.0.0 and dicomviwer 0.0.2 and when I open an MRI by clicking in a slice, when inside the viewer I can't scroll through the slices. Is there an easy way to scroll through the slices in a given series. Each slice is a different .dcm file in my nextcloud instance. Thank you very much for all of your work.

**Comment by ayselafsar** [comment]
Hi @guinhas,
Thanks for your interest. Unfortunately, it is not supported right now but it is in our future roadmap with Worklist.

**Comment by guinhas** [comment]
Hi @ayselafsar ,
Thank you for your answer. Nice to know it's coming in the future. I know this is FOSS and that it will be ready when it's ready, but do you have an idea of when it might be implemented? Sorry for bothering and, again, thank you very much for your work.

**Comment by ayselafsar** [comment]
Hi @guinhas ,
I don't have a timeline for this feature but I'll add it ASAP. I'll leave this open for now. Just out of curiosity, are you personally using DICOM Viewer?

**Comment by guinhas** [comment]
Hi @ayselafsar ,
Thank you very much for your answer! What do you mean by personally? I use it at home... I have a turris omnia router with an lxc ubuntu image running on it, that has nextcloud with dicomviewer installed. I have an interest in storing dicom data because i'm a radiology technician.

**Comment by dueshivan** [comment]
Please give max priority to scroll images, it would be really useful for CT scans and mri

**Comment by Kernel-Error** [comment]
I also would really like to see this feature. B.t.w.: where is your "donation" Button?

**Comment by dueshivan** [comment]
what u mena kernel?

**Comment by ayselafsar** [comment]
Hi all,

I am currently working on this feature. @Kernel-Error You can see [my patreon account](https://www.patreon.com/ayselafsar) for donation. 

Thanks

**Comment by wjwieland** [comment]
In support of guinhas comment, I would like note that I DO use dicomviewer on a regular basis.  It is very helpful!
