### ISSUE TITLE
Cannot preview DCM-file

### ISSUE THREAD

**Issue by belonesox** [ayselafsar/dicomviewer#82]
Cannot preview DCM-file.
Sample: https://cloud.mail.ru/public/68jh/FMYEWM97U or https://drive.google.com/file/d/11VTeFqk5wfVB4_hzeHxsQe19xjo7iy91/view?usp=sharing  (100Mb)
Only «0» displayed on left sidebar.

![image](https://user-images.githubusercontent.com/1609739/144663808-405c4b15-692a-4b70-89ff-ce4ee7e51b87.png)

* No errors in JS-console.

**Client details:**
 - OS: Windows/Linux
 - Browser: Tested in last Firefox and Chrome
 - Version 22
 - Device: desktop

**Comment by Jhickss44** [comment]
Hi, belonesox.  The size dcm file is trouble.  try to open the image set with ohif and the same thing happens. But when trying to open with a viewer under windows it shows me 588 objects. Size is the problem, regards, jhickss44 jhickss@yahoo.com

**Comment by belonesox** [comment]
This DCM file successfully opened with MicroDicom… Is this DCM-file incorrect?
