### ISSUE TITLE
Enable the app for NC 25

### ISSUE THREAD

**Issue by tuxmaster5000** [ayselafsar/dicomviewer#88]
At the moment, the app is marked as not compatible with the release 24 of nc.

**Comment by foxhoundv** [comment]
I don't know if this really would be considered a bug, they probably just haven't had extensive testing to make it show that has been tested and works. I can confirm however that I have it installed on my Nextcloud AIO Docker Instance running 24.0.3. It works just fine I have gone through several DCOM files and it actually seems to run faster that before. Some big files used to take about a minute to load.  now those same ones load in about 10 seconds.

Install went smooth, running it went smooth. The only thing I did not test was uninstalling it... which I don't want to anyways. Other Items work fine.
