### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by guinhas** [ayselafsar/dicomviewer#9]
Hi @ayselafsar ,
When i run nextcloud cron.php it gives this output:

{"reqId":"...","level":3,"time":"...","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: SERVER_NAME at \/var\/www\/nextcloud\/apps\/dicomviewer\/appinfo\/app.php#18","userAgent":"--","version":"13.0.1.1"}
{"reqId":"...","level":3,"time":"...","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"chmod(): Operation not permitted at \/var\/www\/nextcloud\/lib\/private\/Log\/File.php#137","userAgent":"--","version":"13.0.1.1"}

If I remove DICOM viewer, these messages disappear and cron works as expected. Thank you!

**Comment by ayselafsar** [comment]
Hi @guinhas, 
Thanks for the report! Fixed the issue and it will be in the next release in Nextcloud.
