### ISSUE TITLE
Support for Nextcloud 27

### ISSUE THREAD

**Issue by joergmschulz** [ayselafsar/dicomviewer#98]
This app does not install with NC27

**Comment by beankylla** [comment]
i cannot activate it with nextcloud 25.0.6
(had it installed and disabled)

Once i uninstalled it, install is failing

**Comment by FlorianHeigl** [comment]
(also not with 26, just noting due to title change)

**Comment by BastianBalthasarBux** [comment]
Would be great to have a version compatible at least with v 26.

**Comment by finos2** [comment]
any updates? 

i had setup a very good EHR setup and now cannot work on the latest nextcloud version

**Comment by loxK** [comment]
I enabled it as incompatible app, and it works very well (NC 27.1.0)

**Comment by ayselafsar** [comment]
Fixed in v1.2.5
